return
{
  entities =
  {
    {"kr-mineral-water-pumpjack-remnant", {x = -4.5, y = -11.5}, {dir = "south", }},
    {"kr-steel-pipe", {x = -5.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -5.5, y = -8.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -1.5, y = -8.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -1.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -0.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 0.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 1.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 2.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 3.5, y = -9.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"matter-plant-remnant", {x = 8.5, y = -9.5}, {}},
    {"kr-mineral-water-pumpjack-remnant", {x = -8.5, y = -6.5}, {dir = "east", }},
    {"kr-steel-pipe", {x = -6.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -6.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -4.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -5.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-substation-mk2", {x = -3, y = -6}, {dmg = {dmg = {type = "random", min = 0, max = 240}}}},
    {"kr-steel-pipe", {x = -2.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -3.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -1.5, y = -7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-mineral-water-pumpjack-remnant", {x = 0.5, y = -7.5}, {dir = "west", }},
    {"kr-steel-pipe", {x = -6.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 8.5, y = -5.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 8.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 9.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 10.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 11.5, y = -4.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-mineral-water-pumpjack-remnant", {x = -4.5, y = -2.5}, {dir = "west", }},
    {"kr-steel-pipe", {x = 8.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 11.5, y = -3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe-to-ground", {x = 11.5, y = -2.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -8.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -1.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -7.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = -0.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-inserter", {x = 5.5, y = -0.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 250}}}},
    {"kr-superior-transport-belt", {x = 4.5, y = -0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-medium-random-pipes-remnant", {x = 8.5, y = -0.5}, {}},
    {"kr-mineral-water-pumpjack-remnant", {x = -10.5, y = 1.5}, {dir = "east", }},
    {"kr-steel-pipe", {x = -8.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = 0.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = 1.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 4.5, y = 1.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 4.5, y = 0.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-substation-mk2", {x = 12, y = 2}, {dmg = {dmg = {type = "random", min = 0, max = 240}}}},
    {"kr-steel-pipe", {x = -6.5, y = 2.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -6.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -4.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = -5.5, y = 3.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 1.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 0.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 3.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 2.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 5.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 4.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 4.5, y = 2.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 7.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 6.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 9.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 8.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 11.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 10.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-superior-transport-belt", {x = 12.5, y = 3.5}, {dir = "east", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-mineral-water-pumpjack-remnant", {x = -5.5, y = 5.5}, {}},
    {"kr-superior-inserter", {x = 1.5, y = 4.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 250}}}},
    {"kr-superior-inserter", {x = 8.5, y = 4.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 250}}}},
    {"kr-medium-random-pipes-remnant", {x = 1.5, y = 7.5}, {}},
    {"kr-steel-pipe", {x = 4.5, y = 7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-medium-random-pipes-remnant", {x = 8.5, y = 7.5}, {}},
    {"kr-steel-pipe", {x = 11.5, y = 7.5}, {dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe-to-ground", {x = 11.5, y = 6.5}, {dir = "south", dmg = {dmg = {type = "random", min = 0, max = 400}}}},
    {"kr-steel-pipe", {x = 4.5, y = 9.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 4.5, y = 8.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 11.5, y = 8.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 11.5, y = 9.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 5.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 4.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 7.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 6.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 9.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 8.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 11.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
    {"kr-steel-pipe", {x = 10.5, y = 10.5}, {dmg = {dmg = {type = "random", min = 0, max = 300}}}},
  },
}
